### ISSUE TITLE
Question: will it block the PR from merging

### ISSUE THREAD

**Issue by rajbos** [step-security/ai-codewise#18]
Not clear from the docs: will it fail the workflow if comments are placed? 
Could you control that based on the severity of the flaw it found?

**Comment by ashishkurmi** [comment]
Helllo @rajbos,

Currently the bot only provides code comments, it does not approve/block PRs based on its recommendations. The action itself passes once the comments are provided on the PR thread.

**Comment by rajbos** [comment]
Check, makes sense. I would like to see this reflected in the readme a bit more clear though.

**Comment by ashishkurmi** [comment]
Thanks for the feedback @rajbos! We have updated our README as per your recommendation.

**Comment by rajbos** [comment]
Great! Linking the PR for good measure: #20
